import type { Metadata } from "next";
import "./globals.css";
import Page from "@/shared/components/Page";

export const metadata: Metadata = {
  title: "Mol Wise",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Page title="Mol Wise" subtitle="Welcome!">
          {children}
        </Page>
      </body>
    </html>
  );
}
