const elementsData = [
    {
      symbol: "H",
      name: "Hydrogen",
      atomicNumber: 1,
      molarMass: 1.008,
      group: 1,
      period: 1,
      row: 1,
      column: 1,
      showColummNumber: 1,
    },
    {
      symbol: "He",
      name: "Helium",
      atomicNumber: 2,
      molarMass: 4.0026,
      group: 18,
      period: 1,
      row: 1,
      column: 18,
      showColummNumber: 18,
    },
    {
      symbol: "Li",
      name: "Lithium",
      atomicNumber: 3,
      molarMass: 6.94,
      group: 1,
      period: 2,
      row: 2,
      column: 1,
    },
    {
      symbol: "Be",
      name: "Beryllium",
      atomicNumber: 4,
      molarMass: 9.0122,
      group: 2,
      period: 2,
      row: 2,
      column: 2,
      showColummNumber: 2,
    },
    {
      symbol: "B",
      name: "Boron",
      atomicNumber: 5,
      molarMass: 10.81,
      group: 13,
      period: 2,
      row: 2,
      column: 13,
      showColummNumber: 13,
    },
    {
      symbol: "C",
      name: "Carbon",
      atomicNumber: 6,
      molarMass: 12.011,
      group: 14,
      period: 2,
      row: 2,
      column: 14,
      showColummNumber: 14,
    },
    {
      symbol: "N",
      name: "Nitrogen",
      atomicNumber: 7,
      molarMass: 14.007,
      group: 15,
      period: 2,
      row: 2,
      column: 15,
      showColummNumber: 15,
    },
    {
      symbol: "O",
      name: "Oxygen",
      atomicNumber: 8,
      molarMass: 15.999,
      group: 16,
      period: 2,
      row: 2,
      column: 16,
      showColummNumber: 16,
    },
    {
      symbol: "F",
      name: "Fluorine",
      atomicNumber: 9,
      molarMass: 18.998,
      group: 17,
      period: 2,
      row: 2,
      column: 17,
      showColummNumber: 17,
    },
    {
      symbol: "Ne",
      name: "Neon",
      atomicNumber: 10,
      molarMass: 20.18,
      group: 18,
      period: 2,
      row: 2,
      column: 18,
    },
  
    {
      symbol: "Na",
      name: "Sodium",
      atomicNumber: 11,
      molarMass: 22.99,
      group: 1,
      period: 3,
      row: 3,
      column: 1,
    },
    {
      symbol: "Mg",
      name: "Magnesium",
      atomicNumber: 12,
      molarMass: 24.305,
      group: 2,
      period: 3,
      row: 3,
      column: 2,
    },
    {
      symbol: "Al",
      name: "Aluminum",
      atomicNumber: 13,
      molarMass: 26.982,
      group: 13,
      period: 3,
      row: 3,
      column: 13,
    },
    {
      symbol: "Si",
      name: "Silicon",
      atomicNumber: 14,
      molarMass: 28.085,
      group: 14,
      period: 3,
      row: 3,
      column: 14,
    },
    {
      symbol: "P",
      name: "Phosphorus",
      atomicNumber: 15,
      molarMass: 30.974,
      group: 15,
      period: 3,
      row: 3,
      column: 15,
    },
    {
      symbol: "S",
      name: "Sulfur",
      atomicNumber: 16,
      molarMass: 32.06,
      group: 16,
      period: 3,
      row: 3,
      column: 16,
    },
    {
      symbol: "Cl",
      name: "Chlorine",
      atomicNumber: 17,
      molarMass: 35.45,
      group: 17,
      period: 3,
      row: 3,
      column: 17,
    },
    {
      symbol: "Ar",
      name: "Argon",
      atomicNumber: 18,
      molarMass: 39.948,
      group: 18,
      period: 3,
      row: 3,
      column: 18,
    },
  
    {
      symbol: "K",
      name: "Potassium",
      atomicNumber: 19,
      molarMass: 39.098,
      group: 1,
      period: 4,
      row: 4,
      column: 1,
    },
    {
      symbol: "Ca",
      name: "Calcium",
      atomicNumber: 20,
      molarMass: 40.078,
      group: 2,
      period: 4,
      row: 4,
      column: 2,
    },
    {
      symbol: "Sc",
      name: "Scandium",
      atomicNumber: 21,
      molarMass: 44.956,
      group: 3,
      period: 4,
      row: 4,
      column: 3,
      showColummNumber: 3,
    },
    {
      symbol: "Ti",
      name: "Titanium",
      atomicNumber: 22,
      molarMass: 47.867,
      group: 4,
      period: 4,
      row: 4,
      column: 4,
      showColummNumber: 4,
    },
    {
      symbol: "V",
      name: "Vanadium",
      atomicNumber: 23,
      molarMass: 50.942,
      group: 5,
      period: 4,
      row: 4,
      column: 5,
      showColummNumber: 5,
    },
    {
      symbol: "Cr",
      name: "Chromium",
      atomicNumber: 24,
      molarMass: 51.996,
      group: 6,
      period: 4,
      row: 4,
      column: 6,
      showColummNumber: 6,
    },
    {
      symbol: "Mn",
      name: "Manganese",
      atomicNumber: 25,
      molarMass: 54.938,
      group: 7,
      period: 4,
      row: 4,
      column: 7,
      showColummNumber: 7,
    },
    {
      symbol: "Fe",
      name: "Iron",
      atomicNumber: 26,
      molarMass: 55.845,
      group: 8,
      period: 4,
      row: 4,
      column: 8,
      showColummNumber: 8,
    },
    {
      symbol: "Co",
      name: "Cobalt",
      atomicNumber: 27,
      molarMass: 58.933,
      group: 9,
      period: 4,
      row: 4,
      column: 9,
      showColummNumber: 9,
    },
    {
      symbol: "Ni",
      name: "Nickel",
      atomicNumber: 28,
      molarMass: 58.693,
      group: 10,
      period: 4,
      row: 4,
      column: 10,
      showColummNumber: 10,
    },
    {
      symbol: "Cu",
      name: "Copper",
      atomicNumber: 29,
      molarMass: 63.546,
      group: 11,
      period: 4,
      row: 4,
      column: 11,
      showColummNumber: 11,
    },
    {
      symbol: "Zn",
      name: "Zinc",
      atomicNumber: 30,
      molarMass: 65.38,
      group: 12,
      period: 4,
      row: 4,
      column: 12,
      showColummNumber: 12,
    },
    {
      symbol: "Ga",
      name: "Gallium",
      atomicNumber: 31,
      molarMass: 69.723,
      group: 13,
      period: 4,
      row: 4,
      column: 13,
    },
    {
      symbol: "Ge",
      name: "Germanium",
      atomicNumber: 32,
      molarMass: 72.63,
      group: 14,
      period: 4,
      row: 4,
      column: 14,
    },
    {
      symbol: "As",
      name: "Arsenic",
      atomicNumber: 33,
      molarMass: 74.922,
      group: 15,
      period: 4,
      row: 4,
      column: 15,
    },
    {
      symbol: "Se",
      name: "Selenium",
      atomicNumber: 34,
      molarMass: 78.971,
      group: 16,
      period: 4,
      row: 4,
      column: 16,
    },
    {
      symbol: "Br",
      name: "Bromine",
      atomicNumber: 35,
      molarMass: 79.904,
      group: 17,
      period: 4,
      row: 4,
      column: 17,
    },
    {
      symbol: "Kr",
      name: "Krypton",
      atomicNumber: 36,
      molarMass: 83.798,
      group: 18,
      period: 4,
      row: 4,
      column: 18,
    },
  
    {
      symbol: "Rb",
      name: "Rubidium",
      atomicNumber: 37,
      molarMass: 85.468,
      group: 1,
      period: 5,
      row: 5,
      column: 1,
    },
    {
      symbol: "Sr",
      name: "Strontium",
      atomicNumber: 38,
      molarMass: 87.62,
      group: 2,
      period: 5,
      row: 5,
      column: 2,
    },
    {
      symbol: "Y",
      name: "Yttrium",
      atomicNumber: 39,
      molarMass: 88.906,
      group: 3,
      period: 5,
      row: 5,
      column: 3,
    },
    {
      symbol: "Zr",
      name: "Zirconium",
      atomicNumber: 40,
      molarMass: 91.224,
      group: 4,
      period: 5,
      row: 5,
      column: 4,
    },
    {
      symbol: "Nb",
      name: "Niobium",
      atomicNumber: 41,
      molarMass: 92.906,
      group: 5,
      period: 5,
      row: 5,
      column: 5,
    },
    {
      symbol: "Mo",
      name: "Molybdenum",
      atomicNumber: 42,
      molarMass: 95.95,
      group: 6,
      period: 5,
      row: 5,
      column: 6,
    },
    {
      symbol: "Tc",
      name: "Technetium",
      atomicNumber: 43,
      molarMass: 98,
      group: 7,
      period: 5,
      row: 5,
      column: 7,
    },
    {
      symbol: "Ru",
      name: "Ruthenium",
      atomicNumber: 44,
      molarMass: 101.07,
      group: 8,
      period: 5,
      row: 5,
      column: 8,
    },
    {
      symbol: "Rh",
      name: "Rhodium",
      atomicNumber: 45,
      molarMass: 102.91,
      group: 9,
      period: 5,
      row: 5,
      column: 9,
    },
    {
      symbol: "Pd",
      name: "Palladium",
      atomicNumber: 46,
      molarMass: 106.42,
      group: 10,
      period: 5,
      row: 5,
      column: 10,
    },
    {
      symbol: "Ag",
      name: "Silver",
      atomicNumber: 47,
      molarMass: 107.87,
      group: 11,
      period: 5,
      row: 5,
      column: 11,
    },
    {
      symbol: "Cd",
      name: "Cadmium",
      atomicNumber: 48,
      molarMass: 112.41,
      group: 12,
      period: 5,
      row: 5,
      column: 12,
    },
    {
      symbol: "In",
      name: "Indium",
      atomicNumber: 49,
      molarMass: 114.82,
      group: 13,
      period: 5,
      row: 5,
      column: 13,
    },
    {
      symbol: "Sn",
      name: "Tin",
      atomicNumber: 50,
      molarMass: 118.71,
      group: 14,
      period: 5,
      row: 5,
      column: 14,
    },
    {
      symbol: "Sb",
      name: "Antimony",
      atomicNumber: 51,
      molarMass: 121.76,
      group: 15,
      period: 5,
      row: 5,
      column: 15,
    },
    {
      symbol: "Te",
      name: "Tellurium",
      atomicNumber: 52,
      molarMass: 127.6,
      group: 16,
      period: 5,
      row: 5,
      column: 16,
    },
    {
      symbol: "I",
      name: "Iodine",
      atomicNumber: 53,
      molarMass: 126.9,
      group: 17,
      period: 5,
      row: 5,
      column: 17,
    },
    {
      symbol: "Xe",
      name: "Xenon",
      atomicNumber: 54,
      molarMass: 131.29,
      group: 18,
      period: 5,
      row: 5,
      column: 18,
    },
  
    {
      symbol: "Cs",
      name: "Caesium",
      atomicNumber: 55,
      molarMass: 132.91,
      group: 1,
      period: 6,
      row: 6,
      column: 1,
    },
    {
      symbol: "Ba",
      name: "Barium",
      atomicNumber: 56,
      molarMass: 137.33,
      group: 2,
      period: 6,
      row: 6,
      column: 2,
    },
    {
      symbol: "La",
      name: "Lanthanum",
      atomicNumber: 57,
      molarMass: 138.91,
      group: 3,
      period: 6,
      row: 9,
      column: 4,
    },
    {
      symbol: "Ce",
      name: "Cerium",
      atomicNumber: 58,
      molarMass: 140.12,
      group: "Lanthanoid",
      period: 6,
      row: 9,
      column: 5,
    },
    {
      symbol: "Pr",
      name: "Praseodymium",
      atomicNumber: 59,
      molarMass: 140.91,
      group: "Lanthanoid",
      period: 6,
      row: 9,
      column: 6,
    },
    {
      symbol: "Nd",
      name: "Neodymium",
      atomicNumber: 60,
      molarMass: 144.24,
      group: "Lanthanoid",
      period: 6,
      row: 9,
      column: 7,
    },
    {
      symbol: "Pm",
      name: "Promethium",
      atomicNumber: 61,
      molarMass: 145,
      group: "Lanthanoid",
      period: 6,
      row: 9,
      column: 8,
    },
    {
      symbol: "Sm",
      name: "Samarium",
      atomicNumber: 62,
      molarMass: 150.36,
      group: "Lanthanoid",
      period: 6,
      row: 9,
      column: 9,
    },
    {
      symbol: "Eu",
      name: "Europium",
      atomicNumber: 63,
      molarMass: 151.96,
      group: "Lanthanoid",
      period: 6,
      row: 9,
      column: 10,
    },
    {
      symbol: "Gd",
      name: "Gadolinium",
      atomicNumber: 64,
      molarMass: 157.25,
      group: "Lanthanoid",
      period: 6,
      row: 9,
      column: 11,
    },
    {
      symbol: "Tb",
      name: "Terbium",
      atomicNumber: 65,
      molarMass: 158.93,
      group: "Lanthanoid",
      period: 6,
      row: 9,
      column: 12,
    },
    {
      symbol: "Dy",
      name: "Dysprosium",
      atomicNumber: 66,
      molarMass: 162.5,
      group: "Lanthanoid",
      period: 6,
      row: 9,
      column: 13,
    },
    {
      symbol: "Ho",
      name: "Holmium",
      atomicNumber: 67,
      molarMass: 164.93,
      group: "Lanthanoid",
      period: 6,
      row: 9,
      column: 14,
    },
    {
      symbol: "Er",
      name: "Erbium",
      atomicNumber: 68,
      molarMass: 167.26,
      group: "Lanthanoid",
      period: 6,
      row: 9,
      column: 15,
    },
    {
      symbol: "Tm",
      name: "Thulium",
      atomicNumber: 69,
      molarMass: 168.93,
      group: "Lanthanoid",
      period: 6,
      row: 9,
      column: 16,
    },
    {
      symbol: "Yb",
      name: "Ytterbium",
      atomicNumber: 70,
      molarMass: 173.05,
      group: "Lanthanoid",
      period: 6,
      row: 9,
      column: 17,
    },
    {
      symbol: "Lu",
      name: "Lutetium",
      atomicNumber: 71,
      molarMass: 174.97,
      group: 3,
      period: 6,
      row: 9,
      column: 18,
    },
  
    {
      symbol: "Hf",
      name: "Hafnium",
      atomicNumber: 72,
      molarMass: 178.49,
      group: 4,
      period: 6,
      row: 6,
      column: 4,
    },
    {
      symbol: "Ta",
      name: "Tantalum",
      atomicNumber: 73,
      molarMass: 180.95,
      group: 5,
      period: 6,
      row: 6,
      column: 5,
    },
    {
      symbol: "W",
      name: "Tungsten",
      atomicNumber: 74,
      molarMass: 183.84,
      group: 6,
      period: 6,
      row: 6,
      column: 6,
    },
    {
      symbol: "Re",
      name: "Rhenium",
      atomicNumber: 75,
      molarMass: 186.21,
      group: 7,
      period: 6,
      row: 6,
      column: 7,
    },
    {
      symbol: "Os",
      name: "Osmium",
      atomicNumber: 76,
      molarMass: 190.23,
      group: 8,
      period: 6,
      row: 6,
      column: 8,
    },
    {
      symbol: "Ir",
      name: "Iridium",
      atomicNumber: 77,
      molarMass: 192.22,
      group: 9,
      period: 6,
      row: 6,
      column: 9,
    },
    {
      symbol: "Pt",
      name: "Platinum",
      atomicNumber: 78,
      molarMass: 195.08,
      group: 10,
      period: 6,
      row: 6,
      column: 10,
    },
    {
      symbol: "Au",
      name: "Gold",
      atomicNumber: 79,
      molarMass: 196.97,
      group: 11,
      period: 6,
      row: 6,
      column: 11,
    },
    {
      symbol: "Hg",
      name: "Mercury",
      atomicNumber: 80,
      molarMass: 200.59,
      group: 12,
      period: 6,
      row: 6,
      column: 12,
    },
    {
      symbol: "Tl",
      name: "Thallium",
      atomicNumber: 81,
      molarMass: 204.38,
      group: 13,
      period: 6,
      row: 6,
      column: 13,
    },
    {
      symbol: "Pb",
      name: "Lead",
      atomicNumber: 82,
      molarMass: 207.2,
      group: 14,
      period: 6,
      row: 6,
      column: 14,
    },
    {
      symbol: "Bi",
      name: "Bismuth",
      atomicNumber: 83,
      molarMass: 208.98,
      group: 15,
      period: 6,
      row: 6,
      column: 15,
    },
    {
      symbol: "Po",
      name: "Polonium",
      atomicNumber: 84,
      molarMass: 209,
      group: 16,
      period: 6,
      row: 6,
      column: 16,
    },
    {
      symbol: "At",
      name: "Astatine",
      atomicNumber: 85,
      molarMass: 210,
      group: 17,
      period: 6,
      row: 6,
      column: 17,
    },
    {
      symbol: "Rn",
      name: "Radon",
      atomicNumber: 86,
      molarMass: 222,
      group: 18,
      period: 6,
      row: 6,
      column: 18,
    },
  
    {
      symbol: "Fr",
      name: "Francium",
      atomicNumber: 87,
      molarMass: 223,
      group: 1,
      period: 7,
      row: 7,
      column: 1,
    },
    {
      symbol: "Ra",
      name: "Radium",
      atomicNumber: 88,
      molarMass: 226,
      group: 2,
      period: 7,
      row: 7,
      column: 2,
    },
    {
      symbol: "Ac",
      name: "Actinium",
      atomicNumber: 89,
      molarMass: 227,
      group: 3,
      period: 7,
      row: 10,
      column: 4,
    },
    {
      symbol: "Th",
      name: "Thorium",
      atomicNumber: 90,
      molarMass: 232.04,
      group: "Actinoid",
      period: 7,
      row: 10,
      column: 5,
    },
    {
      symbol: "Pa",
      name: "Protactinium",
      atomicNumber: 91,
      molarMass: 231.04,
      group: "Actinoid",
      period: 7,
      row: 10,
      column: 6,
    },
    {
      symbol: "U",
      name: "Uranium",
      atomicNumber: 92,
      molarMass: 238.03,
      group: "Actinoid",
      period: 7,
      row: 10,
      column: 7,
    },
    {
      symbol: "Np",
      name: "Neptunium",
      atomicNumber: 93,
      molarMass: 237,
      group: "Actinoid",
      period: 7,
      row: 10,
      column: 8,
    },
    {
      symbol: "Pu",
      name: "Plutonium",
      atomicNumber: 94,
      molarMass: 244,
      group: "Actinoid",
      period: 7,
      row: 10,
      column: 9,
    },
    {
      symbol: "Am",
      name: "Americium",
      atomicNumber: 95,
      molarMass: 243,
      group: "Actinoid",
      period: 7,
      row: 10,
      column: 10,
    },
    {
      symbol: "Cm",
      name: "Curium",
      atomicNumber: 96,
      molarMass: 247,
      group: "Actinoid",
      period: 7,
      row: 10,
      column: 11,
    },
    {
      symbol: "Bk",
      name: "Berkelium",
      atomicNumber: 97,
      molarMass: 247,
      group: "Actinoid",
      period: 7,
      row: 10,
      column: 12,
    },
    {
      symbol: "Cf",
      name: "Californium",
      atomicNumber: 98,
      molarMass: 251,
      group: "Actinoid",
      period: 7,
      row: 10,
      column: 13,
    },
    {
      symbol: "Es",
      name: "Einsteinium",
      atomicNumber: 99,
      molarMass: 252,
      group: "Actinoid",
      period: 7,
      row: 10,
      column: 14,
    },
    {
      symbol: "Fm",
      name: "Fermium",
      atomicNumber: 100,
      molarMass: 257,
      group: "Actinoid",
      period: 7,
      row: 10,
      column: 15,
    },
    {
      symbol: "Md",
      name: "Mendelevium",
      atomicNumber: 101,
      molarMass: 258,
      group: "Actinoid",
      period: 7,
      row: 10,
      column: 16,
    },
    {
      symbol: "No",
      name: "Nobelium",
      atomicNumber: 102,
      molarMass: 259,
      group: "Actinoid",
      period: 7,
      row: 10,
      column: 17,
    },
    {
      symbol: "Lr",
      name: "Lawrencium",
      atomicNumber: 103,
      molarMass: 262,
      group: 3,
      period: 6,
      row: 10,
      column: 18,
    },
  
    {
      symbol: "Rf",
      name: "Rutherfordium",
      atomicNumber: 104,
      molarMass: 267,
      group: 4,
      period: 7,
      row: 7,
      column: 4,
    },
    {
      symbol: "Db",
      name: "Dubnium",
      atomicNumber: 105,
      molarMass: 270,
      group: 5,
      period: 7,
      row: 7,
      column: 5,
    },
    {
      symbol: "Sg",
      name: "Seaborgium",
      atomicNumber: 106,
      molarMass: 271,
      group: 6,
      period: 7,
      row: 7,
      column: 6,
    },
    {
      symbol: "Bh",
      name: "Bohrium",
      atomicNumber: 107,
      molarMass: 270,
      group: 7,
      period: 7,
      row: 7,
      column: 7,
    },
    {
      symbol: "Hs",
      name: "Hassium",
      atomicNumber: 108,
      molarMass: 277,
      group: 8,
      period: 7,
      row: 7,
      column: 8,
    },
    {
      symbol: "Mt",
      name: "Meitnerium",
      atomicNumber: 109,
      molarMass: 278,
      group: 9,
      period: 7,
      row: 7,
      column: 9,
    },
    {
      symbol: "Ds",
      name: "Darmstadtium",
      atomicNumber: 110,
      molarMass: 281,
      group: 10,
      period: 7,
      row: 7,
      column: 10,
    },
    {
      symbol: "Rg",
      name: "Roentgenium",
      atomicNumber: 111,
      molarMass: 282,
      group: 11,
      period: 7,
      row: 7,
      column: 11,
    },
    {
      symbol: "Cn",
      name: "Copernicium",
      atomicNumber: 112,
      molarMass: 285,
      group: 12,
      period: 7,
      row: 7,
      column: 12,
    },
    {
      symbol: "Nh",
      name: "Nihonium",
      atomicNumber: 113,
      molarMass: 286,
      group: 13,
      period: 7,
      row: 7,
      column: 13,
    },
    {
      symbol: "Fl",
      name: "Flerovium",
      atomicNumber: 114,
      molarMass: 289,
      group: 14,
      period: 7,
      row: 7,
      column: 14,
    },
    {
      symbol: "Mc",
      name: "Moscovium",
      atomicNumber: 115,
      molarMass: 290,
      group: 15,
      period: 7,
      row: 7,
      column: 15,
    },
    {
      symbol: "Lv",
      name: "Livermorium",
      atomicNumber: 116,
      molarMass: 293,
      group: 16,
      period: 7,
      row: 7,
      column: 16,
    },
    {
      symbol: "Ts",
      name: "Tennessine",
      atomicNumber: 117,
      molarMass: 294,
      group: 17,
      period: 7,
      row: 7,
      column: 17,
    },
    {
      symbol: "Og",
      name: "Oganesson",
      atomicNumber: 118,
      molarMass: 294,
      group: 18,
      period: 7,
      row: 7,
      column: 18,
    },
  ];
  
  export default elementsData;
  