const elementsData = [
  {
    symbol: "H",
    name: "Hydrogen",
    atomicNumber: 1,
    molarMass: 1.008,
    category: "Nonmetal",
    standardState: "gas",
    electronConfiguration: "1s1",
    oxidationStates: "+1, -1",
    electronegativity: 2.2,
    atomicRadius: "120 pm",
    ionizationEnergy: "13.598 eV",
    electronAffinity: "0.754 eV",
    meltingPoint: "13.81 K",
    boilingPoint: "20.28 K",
    density: "0.00008988 g/cm³",
    yearDiscovered: "1766",
    group: 1,
    period: 1,
    row: 1,
    column: 1,
    showColummNumber: 1,
  },
  {
    symbol: "He",
    name: "Helium",
    atomicNumber: 2,
    molarMass: 4.0026,
    category: "Noble gas",
    standardState: "gas",
    electronConfiguration: "1s2",
    oxidationStates: "0",
    atomicRadius: "140 pm",
    ionizationEnergy: "24.587 eV",
    meltingPoint: "0.95 K",
    boilingPoint: "4.22 K",
    density: "0.0001785 g/cm³",
    yearDiscovered: "1868",
    group: 18,
    period: 1,
    row: 1,
    column: 18,
    showColummNumber: 18,
  },
  {
    symbol: "Li",
    name: "Lithium",
    atomicNumber: 3,
    molarMass: 6.94,
    category: "Alkali metal",
    standardState: "solid",
    electronConfiguration: "[He]2s1",
    oxidationStates: "+1",
    electronegativity: 0.98,
    atomicRadius: "182 pm",
    ionizationEnergy: "5.392 eV",
    electronAffinity: "0.618 eV",
    meltingPoint: "453.65 K",
    boilingPoint: "1603 K",
    density: "0.534 g/cm³",
    yearDiscovered: "1817",
    group: 1,
    period: 2,
    row: 2,
    column: 1,
  },
  {
    symbol: "Be",
    name: "Beryllium",
    atomicNumber: 4,
    molarMass: 9.0122,
    category: "Alkaline earth metal",
    standardState: "solid",
    electronConfiguration: "[He]2s2",
    oxidationStates: "+2",
    electronegativity: 1.57,
    atomicRadius: "153 pm",
    ionizationEnergy: "9.323 eV",
    meltingPoint: "1560 K",
    boilingPoint: "2742 K",
    density: "1.85 g/cm³",
    yearDiscovered: "1798",
    group: 2,
    period: 2,
    row: 2,
    column: 2,
    showColummNumber: 2,
  },
  {
    symbol: "B",
    name: "Boron",
    atomicNumber: 5,
    molarMass: 10.81,
    category: "Metalloid",
    standardState: "solid",
    electronConfiguration: "[He]2s22p1",
    oxidationStates: "+3",
    electronegativity: 2.04,
    atomicRadius: "192 pm",
    ionizationEnergy: "8.298 eV",
    electronAffinity: "0.277 eV",
    meltingPoint: "2349 K",
    boilingPoint: "4200 K",
    density: "2.34 g/cm³",
    yearDiscovered: "1808",
    group: 13,
    period: 2,
    row: 2,
    column: 13,
    showColummNumber: 13,
  },
  {
    symbol: "C",
    name: "Carbon",
    atomicNumber: 6,
    molarMass: 12.011,
    category: "Nonmetal",
    standardState: "solid",
    electronConfiguration: "[He]2s22p2",
    oxidationStates: "+4, +2, -4",
    electronegativity: 2.55,
    atomicRadius: "170 pm",
    ionizationEnergy: "11.260 eV",
    electronAffinity: "1.263 eV",
    meltingPoint: "3823 K",
    boilingPoint: "4098 K",
    density: "2.267 g/cm³",
    yearDiscovered: "ancient",
    group: 14,
    period: 2,
    row: 2,
    column: 14,
    showColummNumber: 14,
  },
  {
    symbol: "N",
    name: "Nitrogen",
    atomicNumber: 7,
    molarMass: 14.007,
    category: "Nonmetal",
    standardState: "gas",
    electronConfiguration: "[He]2s22p3",
    oxidationStates: "+5, +4, +3, +2, +1, -1, -2, -3",
    electronegativity: 3.04,
    atomicRadius: "155 pm",
    ionizationEnergy: "14.534 eV",
    meltingPoint: "63.15 K",
    boilingPoint: "77.36 K",
    density: "0.0012506 g/cm³",
    yearDiscovered: "1772",
    group: 15,
    period: 2,
    row: 2,
    column: 15,
    showColummNumber: 15,
  },
  {
    symbol: "O",
    name: "Oxygen",
    atomicNumber: 8,
    molarMass: 15.999,
    category: "Nonmetal",
    standardState: "gas",
    electronConfiguration: "[He]2s22p4",
    oxidationStates: "-2",
    electronegativity: 3.44,
    atomicRadius: "152 pm",
    ionizationEnergy: "13.618 eV",
    electronAffinity: "1.461 eV",
    meltingPoint: "54.36 K",
    boilingPoint: "90.20 K",
    density: "0.001429 g/cm³",
    yearDiscovered: "1774",
    group: 16,
    period: 2,
    row: 2,
    column: 16,
    showColummNumber: 16,
  },
  {
    symbol: "F",
    name: "Fluorine",
    atomicNumber: 9,
    molarMass: 18.998,
    category: "Halogen",
    standardState: "gas",
    electronConfiguration: "[He]2s22p5",
    oxidationStates: "-1",
    electronegativity: 3.98,
    atomicRadius: "135 pm",
    ionizationEnergy: "17.423 eV",
    electronAffinity: "3.339 eV",
    meltingPoint: "53.53 K",
    boilingPoint: "85.03 K",
    density: "0.001696 g/cm³",
    yearDiscovered: "1670",
    group: 17,
    period: 2,
    row: 2,
    column: 17,
    showColummNumber: 17,
  },
  {
    symbol: "Ne",
    name: "Neon",
    atomicNumber: 10,
    molarMass: 20.18,
    category: "Noble gas",
    standardState: "gas",
    electronConfiguration: "[He]2s22p6",
    oxidationStates: "0",
    atomicRadius: "154 pm",
    ionizationEnergy: "21.565 eV",
    meltingPoint: "24.56 K",
    boilingPoint: "27.07 K",
    density: "0.0008999 g/cm³",
    yearDiscovered: "1898",
    group: 18,
    period: 2,
    row: 2,
    column: 18,
  },
  {
    symbol: "Na",
    name: "Sodium",
    atomicNumber: 11,
    molarMass: 22.989769,
    category: "Alkali metal",
    standardState: "solid",
    electronConfiguration: "[Ne]3s1",
    oxidationStates: "+1",
    electronegativity: 0.93,
    atomicRadius: "227 pm",
    ionizationEnergy: "5.139 eV",
    electronAffinity: "0.548 eV",
    meltingPoint: "370.95 K",
    boilingPoint: "1156 K",
    density: "0.97 g/cm³",
    yearDiscovered: "1807",
    group: 1,
    period: 3,
    row: 3,
    column: 1,
  },
  {
    symbol: "Mg",
    name: "Magnesium",
    atomicNumber: 12,
    molarMass: 24.305,
    category: "Alkaline earth metal",
    standardState: "solid",
    electronConfiguration: "[Ne]3s2",
    oxidationStates: "+2",
    electronegativity: 1.31,
    atomicRadius: "173 pm",
    ionizationEnergy: "7.646 eV",
    meltingPoint: "923 K",
    boilingPoint: "1363 K",
    density: "1.74 g/cm³",
    yearDiscovered: "1808",
    group: 2,
    period: 3,
    row: 3,
    column: 2,
  },
  {
    symbol: "Al",
    name: "Aluminum",
    atomicNumber: 13,
    molarMass: 26.981538,
    category: "Post-transition metal",
    standardState: "solid",
    electronConfiguration: "[Ne]3s23p1",
    oxidationStates: "+3",
    electronegativity: 1.61,
    atomicRadius: "184 pm",
    ionizationEnergy: "5.986 eV",
    electronAffinity: "0.441 eV",
    meltingPoint: "933.437 K",
    boilingPoint: "2792 K",
    density: "2.70 g/cm³",
    yearDiscovered: "ancient",
    group: 13,
    period: 3,
    row: 3,
    column: 13,
  },
  {
    symbol: "Si",
    name: "Silicon",
    atomicNumber: 14,
    molarMass: 28.085,
    category: "Metalloid",
    standardState: "solid",
    electronConfiguration: "[Ne]3s23p2",
    oxidationStates: "+4, +2, -4",
    electronegativity: 1.9,
    atomicRadius: "210 pm",
    ionizationEnergy: "8.152 eV",
    electronAffinity: "1.385 eV",
    meltingPoint: "1687 K",
    boilingPoint: "3538 K",
    density: "2.3296 g/cm³",
    yearDiscovered: "1854",
    group: 14,
    period: 3,
    row: 3,
    column: 14,
  },
  {
    symbol: "P",
    name: "Phosphorus",
    atomicNumber: 15,
    molarMass: 30.973762,
    category: "Nonmetal",
    standardState: "solid",
    electronConfiguration: "[Ne]3s23p3",
    oxidationStates: "+5, +3, -3",
    electronegativity: 2.19,
    atomicRadius: "180 pm",
    ionizationEnergy: "10.487 eV",
    electronAffinity: "0.746 eV",
    meltingPoint: "317.3 K",
    boilingPoint: "553.65 K",
    density: "1.82 g/cm³",
    yearDiscovered: "1669",
    group: 15,
    period: 3,
    row: 3,
    column: 15,
  },
  {
    symbol: "S",
    name: "Sulfur",
    atomicNumber: 16,
    molarMass: 32.07,
    category: "Nonmetal",
    standardState: "solid",
    electronConfiguration: "[Ne]3s23p4",
    oxidationStates: "+6, +4, -2",
    electronegativity: 2.58,
    atomicRadius: "180 pm",
    ionizationEnergy: "10.360 eV",
    electronAffinity: "2.077 eV",
    meltingPoint: "388.36 K",
    boilingPoint: "717.75 K",
    density: "2.067 g/cm³",
    yearDiscovered: "ancient",
    group: 16,
    period: 3,
    row: 3,
    column: 16,
  },
  {
    symbol: "Cl",
    name: "Chlorine",
    atomicNumber: 17,
    molarMass: 35.45,
    category: "Halogen",
    standardState: "gas",
    electronConfiguration: "[Ne]3s23p5",
    oxidationStates: "+7, +5, +1, -1",
    electronegativity: 3.16,
    atomicRadius: "175 pm",
    ionizationEnergy: "12.968 eV",
    electronAffinity: "3.617 eV",
    meltingPoint: "171.65 K",
    boilingPoint: "239.11 K",
    density: "0.003214 g/cm³",
    yearDiscovered: "1774",
    group: 17,
    period: 3,
    row: 3,
    column: 17,
  },
  {
    symbol: "Ar",
    name: "Argon",
    atomicNumber: 18,
    molarMass: 39.948,
    category: "Noble gas",
    standardState: "gas",
    electronConfiguration: "[Ne]3s23p6",
    oxidationStates: "0",
    atomicRadius: "188 pm",
    ionizationEnergy: "15.760 eV",
    meltingPoint: "83.8 K",
    boilingPoint: "87.3 K",
    density: "0.0017837 g/cm³",
    yearDiscovered: "1894",
    group: 18,
    period: 3,
    row: 3,
    column: 18,
  },
  {
    symbol: "K",
    name: "Potassium",
    atomicNumber: 19,
    molarMass: 39.0983,
    category: "Alkali metal",
    standardState: "solid",
    electronConfiguration: "[Ar]4s1",
    oxidationStates: "+1",
    electronegativity: 0.82,
    atomicRadius: "275 pm",
    ionizationEnergy: "4.341 eV",
    electronAffinity: "0.501 eV",
    meltingPoint: "336.53 K",
    boilingPoint: "1032 K",
    density: "0.89 g/cm³",
    yearDiscovered: "1807",
    group: 1,
    period: 4,
    row: 4,
    column: 1,
  },
  {
    symbol: "Ca",
    name: "Calcium",
    atomicNumber: 20,
    molarMass: 40.078,
    category: "Alkaline earth metal",
    standardState: "solid",
    electronConfiguration: "[Ar]4s2",
    oxidationStates: "+2",
    electronegativity: 1.0,
    atomicRadius: "231 pm",
    ionizationEnergy: "6.113 eV",
    meltingPoint: "1115 K",
    boilingPoint: "1757 K",
    density: "1.54 g/cm³",
    yearDiscovered: "ancient",
    group: 2,
    period: 4,
    row: 4,
    column: 2,
  },
  {
    symbol: "Sc",
    name: "Scandium",
    atomicNumber: 21,
    molarMass: 44.955908,
    category: "Transition metal",
    standardState: "solid",
    electronConfiguration: "[Ar]4s23d1",
    oxidationStates: "+3",
    electronegativity: 1.36,
    atomicRadius: "211 pm",
    ionizationEnergy: "6.561 eV",
    electronAffinity: "0.188 eV",
    meltingPoint: "1814 K",
    boilingPoint: "3109 K",
    density: "2.99 g/cm³",
    yearDiscovered: "1879",
    group: 3,
    period: 4,
    row: 4,
    column: 3,
  },
  {
    symbol: "Ti",
    name: "Titanium",
    atomicNumber: 22,
    molarMass: 47.867,
    category: "Transition metal",
    standardState: "solid",
    electronConfiguration: "[Ar]4s23d2",
    oxidationStates: "+4, +3, +2",
    electronegativity: 1.54,
    atomicRadius: "187 pm",
    ionizationEnergy: "6.828 eV",
    electronAffinity: "0.079 eV",
    meltingPoint: "1941 K",
    boilingPoint: "3560 K",
    density: "4.5 g/cm³",
    yearDiscovered: "1791",
    group: 4,
    period: 4,
    row: 4,
    column: 4,
  },
  {
    symbol: "V",
    name: "Vanadium",
    atomicNumber: 23,
    molarMass: 50.9415,
    category: "Transition metal",
    standardState: "solid",
    electronConfiguration: "[Ar]4s23d3",
    oxidationStates: "+5, +4, +3, +2",
    electronegativity: 1.63,
    atomicRadius: "179 pm",
    ionizationEnergy: "6.746 eV",
    electronAffinity: "0.525 eV",
    meltingPoint: "2183 K",
    boilingPoint: "3680 K",
    density: "6.0 g/cm³",
    yearDiscovered: "1801",
    group: 5,
    period: 4,
    row: 4,
    column: 5,
  },
  {
    symbol: "Cr",
    name: "Chromium",
    atomicNumber: 24,
    molarMass: 51.9961,
    category: "Transition metal",
    standardState: "solid",
    electronConfiguration: "[Ar]3d54s1",
    oxidationStates: "+6, +3, +2",
    electronegativity: 1.66,
    atomicRadius: "189 pm",
    ionizationEnergy: "6.767 eV",
    electronAffinity: "0.666 eV",
    meltingPoint: "2180 K",
    boilingPoint: "2944 K",
    density: "7.15 g/cm³",
    yearDiscovered: "1797",
    group: 6,
    period: 4,
    row: 4,
    column: 6,
  },
  {
    symbol: "Mn",
    name: "Manganese",
    atomicNumber: 25,
    molarMass: 54.938044,
    category: "Transition metal",
    standardState: "solid",
    electronConfiguration: "[Ar]4s23d5",
    oxidationStates: "+7, +4, +3, +2",
    electronegativity: 1.55,
    atomicRadius: "197 pm",
    ionizationEnergy: "7.434 eV",
    meltingPoint: "1519 K",
    boilingPoint: "2334 K",
    density: "7.3 g/cm³",
    yearDiscovered: "1774",
    group: 7,
    period: 4,
    row: 4,
    column: 7,
  },
  {
    symbol: "Fe",
    name: "Iron",
    atomicNumber: 26,
    molarMass: 55.845,
    category: "Transition metal",
    standardState: "solid",
    electronConfiguration: "[Ar]4s23d6",
    oxidationStates: "+3, +2",
    electronegativity: 1.83,
    atomicRadius: "194 pm",
    ionizationEnergy: "7.902 eV",
    electronAffinity: "0.163 eV",
    meltingPoint: "1811 K",
    boilingPoint: "3134 K",
    density: "7.874 g/cm³",
    yearDiscovered: "ancient",
    group: 8,
    period: 4,
    row: 4,
    column: 8,
  },
  {
    symbol: "Co",
    name: "Cobalt",
    atomicNumber: 27,
    molarMass: 58.933194,
    category: "Transition metal",
    standardState: "solid",
    electronConfiguration: "[Ar]4s23d7",
    oxidationStates: "+3, +2",
    electronegativity: 1.88,
    atomicRadius: "192 pm",
    ionizationEnergy: "7.881 eV",
    electronAffinity: "0.661 eV",
    meltingPoint: "1768 K",
    boilingPoint: "3200 K",
    density: "8.86 g/cm³",
    yearDiscovered: "1735",
    group: 9,
    period: 4,
    row: 4,
    column: 9,
  },
  {
    symbol: "Ni",
    name: "Nickel",
    atomicNumber: 28,
    molarMass: 58.6934,
    category: "Transition metal",
    standardState: "solid",
    electronConfiguration: "[Ar]4s23d8",
    oxidationStates: "+3, +2",
    electronegativity: 1.91,
    atomicRadius: "163 pm",
    ionizationEnergy: "7.640 eV",
    electronAffinity: "1.156 eV",
    meltingPoint: "1728 K",
    boilingPoint: "3186 K",
    density: "8.912 g/cm³",
    yearDiscovered: "1751",
    group: 10,
    period: 4,
    row: 4,
    column: 10,
  },
  {
    symbol: "Cu",
    name: "Copper",
    atomicNumber: 29,
    molarMass: 63.546,
    category: "Transition metal",
    standardState: "solid",
    electronConfiguration: "[Ar]4s13d10",
    oxidationStates: "+2, +1",
    electronegativity: 1.9,
    atomicRadius: "140 pm",
    ionizationEnergy: "7.726 eV",
    electronAffinity: "1.228 eV",
    meltingPoint: "1357.77 K",
    boilingPoint: "2835 K",
    density: "8.933 g/cm³",
    yearDiscovered: "ancient",
    group: 11,
    period: 4,
    row: 4,
    column: 11,
  },
  {
    symbol: "Zn",
    name: "Zinc",
    atomicNumber: 30,
    molarMass: 65.38,
    category: "Transition metal",
    standardState: "solid",
    electronConfiguration: "[Ar]4s23d10",
    oxidationStates: "+2",
    electronegativity: 1.65,
    atomicRadius: "139 pm",
    ionizationEnergy: "9.394 eV",
    meltingPoint: "692.68 K",
    boilingPoint: "1180 K",
    density: "7.134 g/cm³",
    yearDiscovered: "1746",
    group: 12,
    period: 4,
    row: 4,
    column: 12,
  },
  {
    symbol: "Ga",
    name: "Gallium",
    atomicNumber: 31,
    molarMass: 69.723,
    category: "Post-transition metal",
    standardState: "solid",
    electronConfiguration: "[Ar]4s23d104p1",
    oxidationStates: "+3",
    electronegativity: 1.81,
    atomicRadius: "187 pm",
    ionizationEnergy: "5.999 eV",
    electronAffinity: "0.3 eV",
    meltingPoint: "302.91 K",
    boilingPoint: "2477 K",
    density: "5.91 g/cm³",
    yearDiscovered: "1875",
    group: 13,
    period: 4,
    row: 4,
    column: 13,
  },
  {
    symbol: "Ge",
    name: "Germanium",
    atomicNumber: 32,
    molarMass: 72.63,
    category: "Metalloid",
    standardState: "solid",
    electronConfiguration: "[Ar]4s23d104p2",
    oxidationStates: "+4, +2",
    electronegativity: 2.01,
    atomicRadius: "211 pm",
    ionizationEnergy: "7.900 eV",
    electronAffinity: "1.35 eV",
    meltingPoint: "1211.4 K",
    boilingPoint: "3106 K",
    density: "5.323 g/cm³",
    yearDiscovered: "1886",
    group: 14,
    period: 4,
    row: 4,
    column: 14,
  },
  {
    symbol: "As",
    name: "Arsenic",
    atomicNumber: 33,
    molarMass: 74.9216,
    category: "Metalloid",
    standardState: "solid",
    electronConfiguration: "[Ar]4s23d104p3",
    oxidationStates: "+5, +3, -3",
    electronegativity: 2.18,
    atomicRadius: "185 pm",
    ionizationEnergy: "9.815 eV",
    electronAffinity: "0.81 eV",
    meltingPoint: "1090 K",
    boilingPoint: "887 K",
    density: "5.776 g/cm³",
    yearDiscovered: "ancient",
    group: 15,
    period: 4,
    row: 4,
    column: 15,
  },
  {
    symbol: "Se",
    name: "Selenium",
    atomicNumber: 34,
    molarMass: 78.971,
    category: "Nonmetal",
    standardState: "solid",
    electronConfiguration: "[Ar]4s23d104p4",
    oxidationStates: "+6, +4, -2",
    electronegativity: 2.55,
    atomicRadius: "190 pm",
    ionizationEnergy: "9.010 eV",
    electronAffinity: "1.971 eV",
    meltingPoint: "494 K",
    boilingPoint: "958 K",
    density: "4.809 g/cm³",
    yearDiscovered: "1817",
    group: 16,
    period: 4,
    row: 4,
    column: 16,
  },
  {
    symbol: "Br",
    name: "Bromine",
    atomicNumber: 35,
    molarMass: 79.904,
    category: "Halogen",
    standardState: "liquid",
    electronConfiguration: "[Ar]4s23d104p5",
    oxidationStates: "+5, +1, -1",
    electronegativity: 2.96,
    atomicRadius: "185 pm",
    ionizationEnergy: "11.814 eV",
    electronAffinity: "3.365 eV",
    meltingPoint: "265.8 K",
    boilingPoint: "332.0 K",
    density: "3.1028 g/cm³",
    yearDiscovered: "1826",
    group: 17,
    period: 4,
    row: 4,
    column: 17,
  },
  {
    symbol: "Kr",
    name: "Krypton",
    atomicNumber: 36,
    molarMass: 83.798,
    category: "Noble gas",
    standardState: "gas",
    electronConfiguration: "[Ar]4s23d104p6",
    oxidationStates: "0",
    electronegativity: 3.0,
    atomicRadius: "202 pm",
    ionizationEnergy: "13.999 eV",
    meltingPoint: "115.79 K",
    boilingPoint: "119.93 K",
    density: "0.003733 g/cm³",
    yearDiscovered: "1898",
    group: 18,
    period: 4,
    row: 4,
    column: 18,
  },
  {
    symbol: "Rb",
    name: "Rubidium",
    atomicNumber: 37,
    molarMass: 85.4678,
    category: "Alkali metal",
    standardState: "solid",
    electronConfiguration: "[Kr]5s1",
    oxidationStates: "+1",
    electronegativity: 0.82,
    atomicRadius: "303 pm",
    ionizationEnergy: "4.177 eV",
    electronAffinity: "0.486 eV",
    meltingPoint: "312.46 K",
    boilingPoint: "961 K",
    density: "1.532 g/cm³",
    yearDiscovered: "1861",
    group: 1,
    period: 5,
    row: 5,
    column: 1,
  },
  {
    symbol: "Sr",
    name: "Strontium",
    atomicNumber: 38,
    molarMass: 87.62,
    category: "Alkaline earth metal",
    standardState: "solid",
    electronConfiguration: "[Kr]5s2",
    oxidationStates: "+2",
    electronegativity: 0.95,
    atomicRadius: "249 pm",
    ionizationEnergy: "5.695 eV",
    meltingPoint: "1050 K",
    boilingPoint: "1655 K",
    density: "2.64 g/cm³",
    yearDiscovered: "1790",
    group: 2,
    period: 5,
    row: 5,
    column: 2,
  },
  {
    symbol: "Y",
    name: "Yttrium",
    atomicNumber: 39,
    molarMass: 88.90584,
    category: "Transition metal",
    standardState: "solid",
    electronConfiguration: "[Kr]4d15s2",
    oxidationStates: "+3",
    electronegativity: 1.22,
    atomicRadius: "212 pm",
    ionizationEnergy: "6.217 eV",
    meltingPoint: "1799 K",
    boilingPoint: "3609 K",
    density: "4.469 g/cm³",
    yearDiscovered: "1794",
    group: 3,
    period: 5,
    row: 5,
    column: 3,
  },
  {
    symbol: "Zr",
    name: "Zirconium",
    atomicNumber: 40,
    molarMass: 91.224,
    category: "Transition metal",
    standardState: "solid",
    electronConfiguration: "[Kr]4d25s2",
    oxidationStates: "+4",
    electronegativity: 1.33,
    atomicRadius: "206 pm",
    ionizationEnergy: "6.634 eV",
    meltingPoint: "2128 K",
    boilingPoint: "4682 K",
    density: "6.506 g/cm³",
    yearDiscovered: "1789",
    group: 4,
    period: 5,
    row: 5,
    column: 4,
  },
  {
    symbol: "Nb",
    name: "Niobium",
    atomicNumber: 41,
    molarMass: 92.90637,
    category: "Transition metal",
    standardState: "solid",
    electronConfiguration: "[Kr]4d45s1",
    oxidationStates: "+5",
    electronegativity: 1.6,
    atomicRadius: "198 pm",
    ionizationEnergy: "6.759 eV",
    meltingPoint: "2750 K",
    boilingPoint: "5017 K",
    density: "8.57 g/cm³",
    yearDiscovered: "1801",
    group: 5,
    period: 5,
    row: 5,
    column: 5,
  },
  {
    symbol: "Mo",
    name: "Molybdenum",
    atomicNumber: 42,
    molarMass: 95.95,
    category: "Transition metal",
    standardState: "solid",
    electronConfiguration: "[Kr]4d55s1",
    oxidationStates: "+6, +5, +4, +3, +2, +1, 0, -1, -2, -4",
    electronegativity: 2.16,
    atomicRadius: "190 pm",
    ionizationEnergy: "7.092 eV",
    meltingPoint: "2896 K",
    boilingPoint: "4912 K",
    density: "10.22 g/cm³",
    yearDiscovered: "1778",
    group: 6,
    period: 5,
    row: 5,
    column: 6,
  },
  {
    symbol: "Tc",
    name: "Technetium",
    atomicNumber: 43,
    molarMass: 98,
    category: "Transition metal",
    standardState: "solid",
    electronConfiguration: "[Kr]4d65s1",
    oxidationStates: "+7, +6, +5, +4, +3, +2, +1, 0, -1",
    electronegativity: 1.9,
    atomicRadius: "183 pm",
    ionizationEnergy: "7.28 eV",
    meltingPoint: "2430 K",
    boilingPoint: "4538 K",
    density: "11.5 g/cm³",
    yearDiscovered: "1937",
    group: 7,
    period: 5,
    row: 5,
    column: 7,
  },
  {
    symbol: "Ru",
    name: "Ruthenium",
    atomicNumber: 44,
    molarMass: 101.07,
    category: "Transition metal",
    standardState: "solid",
    electronConfiguration: "[Kr]4d75s1",
    oxidationStates: "+8, +6, +4, +3, +2, +1, 0, -1, -2",
    electronegativity: 2.2,
    atomicRadius: "178 pm",
    ionizationEnergy: "7.361 eV",
    meltingPoint: "2607 K",
    boilingPoint: "4423 K",
    density: "12.37 g/cm³",
    yearDiscovered: "1844",
    group: 8,
    period: 5,
    row: 5,
    column: 8,
  },
  {
    symbol: "Rh",
    name: "Rhodium",
    atomicNumber: 45,
    molarMass: 102.9055,
    category: "Transition metal",
    standardState: "solid",
    electronConfiguration: "[Kr]4d85s1",
    oxidationStates: "+4, +3, +2, +1, 0, -1",
    electronegativity: 2.28,
    atomicRadius: "173 pm",
    ionizationEnergy: "7.459 eV",
    meltingPoint: "2237 K",
    boilingPoint: "3968 K",
    density: "12.41 g/cm³",
    yearDiscovered: "1803",
    group: 9,
    period: 5,
    row: 5,
    column: 9,
  },
  {
    symbol: "Pd",
    name: "Palladium",
    atomicNumber: 46,
    molarMass: 106.42,
    category: "Transition metal",
    standardState: "solid",
    electronConfiguration: "[Kr]4d10",
    oxidationStates: "+4, +2, 0",
    electronegativity: 2.2,
    atomicRadius: "169 pm",
    ionizationEnergy: "8.337 eV",
    meltingPoint: "1828.05 K",
    boilingPoint: "3236 K",
    density: "12.02 g/cm³",
    yearDiscovered: "1803",
    group: 10,
    period: 5,
    row: 5,
    column: 10,
  },
  {
    symbol: "Ag",
    name: "Silver",
    atomicNumber: 47,
    molarMass: 107.8682,
    category: "Transition metal",
    standardState: "solid",
    electronConfiguration: "[Kr]4d105s1",
    oxidationStates: "+1",
    electronegativity: 1.93,
    atomicRadius: "165 pm",
    ionizationEnergy: "7.576 eV",
    electronAffinity: "1.302 eV",
    meltingPoint: "1234.93 K",
    boilingPoint: "2435 K",
    density: "10.501 g/cm³",
    yearDiscovered: "ancient",
    group: 11,
    period: 5,
    row: 5,
    column: 11,
  },
  {
    symbol: "Cd",
    name: "Cadmium",
    atomicNumber: 48,
    molarMass: 112.414,
    category: "Transition metal",
    standardState: "solid",
    electronConfiguration: "[Kr]4d105s2",
    oxidationStates: "+2",
    electronegativity: 1.69,
    atomicRadius: "161 pm",
    ionizationEnergy: "8.994 eV",
    meltingPoint: "594.22 K",
    boilingPoint: "1040 K",
    density: "8.65 g/cm³",
    yearDiscovered: "1817",
    group: 12,
    period: 5,
    row: 5,
    column: 12,
  },
  {
    symbol: "In",
    name: "Indium",
    atomicNumber: 49,
    molarMass: 114.818,
    category: "Post-transition metal",
    standardState: "solid",
    electronConfiguration: "[Kr]4d105s25p1",
    oxidationStates: "+3, +1",
    electronegativity: 1.78,
    atomicRadius: "156 pm",
    ionizationEnergy: "5.786 eV",
    meltingPoint: "429.75 K",
    boilingPoint: "2345 K",
    density: "7.31 g/cm³",
    yearDiscovered: "1863",
    group: 13,
    period: 5,
    row: 5,
    column: 13,
  },
  {
    symbol: "Sn",
    name: "Tin",
    atomicNumber: 50,
    molarMass: 118.71,
    category: "Post-transition metal",
    standardState: "solid",
    electronConfiguration: "[Kr]4d105s25p2",
    oxidationStates: "+4, +2",
    electronegativity: 1.96,
    atomicRadius: "145 pm",
    ionizationEnergy: "7.344 eV",
    meltingPoint: "505.08 K",
    boilingPoint: "2875 K",
    density: "7.287 g/cm³",
    yearDiscovered: "ancient",
    group: 14,
    period: 5,
    row: 5,
    column: 14,
  },
  {
    symbol: "Sb",
    name: "Antimony",
    atomicNumber: 51,
    molarMass: 121.76,
    category: "Metalloid",
    standardState: "solid",
    electronConfiguration: "[Kr]4d105s25p3",
    oxidationStates: "+5, +3, -3",
    electronegativity: 2.05,
    atomicRadius: "133 pm",
    ionizationEnergy: "8.608 eV",
    meltingPoint: "903.78 K",
    boilingPoint: "1860 K",
    density: "6.685 g/cm³",
    yearDiscovered: "ancient",
    group: 15,
    period: 5,
    row: 5,
    column: 15,
  },
  {
    symbol: "Te",
    name: "Tellurium",
    atomicNumber: 52,
    molarMass: 127.6,
    category: "Metalloid",
    standardState: "solid",
    electronConfiguration: "[Kr]4d105s25p4",
    oxidationStates: "+6, +4, -2",
    electronegativity: 2.1,
    atomicRadius: "123 pm",
    ionizationEnergy: "9.0096 eV",
    meltingPoint: "722.66 K",
    boilingPoint: "1261 K",
    density: "6.24 g/cm³",
    yearDiscovered: "1782",
    group: 16,
    period: 5,
    row: 5,
    column: 16,
  },
  {
    symbol: "I",
    name: "Iodine",
    atomicNumber: 53,
    molarMass: 126.90447,
    category: "Halogen",
    standardState: "solid",
    electronConfiguration: "[Kr]4d105s25p5",
    oxidationStates: "+7, +5, +1, -1",
    electronegativity: 2.66,
    atomicRadius: "115 pm",
    ionizationEnergy: "10.451 eV",
    electronAffinity: "3.059 eV",
    meltingPoint: "386.85 K",
    boilingPoint: "457.55 K",
    density: "4.93 g/cm³",
    yearDiscovered: "1811",
    group: 17,
    period: 5,
    row: 5,
    column: 17,
  },
  {
    symbol: "Xe",
    name: "Xenon",
    atomicNumber: 54,
    molarMass: 131.293,
    category: "Noble gas",
    standardState: "gas",
    electronConfiguration: "[Kr]4d105s25p6",
    oxidationStates: "0",
    electronegativity: 2.6,
    atomicRadius: "108 pm",
    ionizationEnergy: "12.130 eV",
    meltingPoint: "161.36 K",
    boilingPoint: "165.03 K",
    density: "0.005887 g/cm³",
    yearDiscovered: "1898",
    group: 18,
    period: 5,
    row: 5,
    column: 18,
  },
  {
    symbol: "Cs",
    name: "Cesium",
    atomicNumber: 55,
    molarMass: 132.90545196,
    category: "Alkali metal",
    standardState: "solid",
    electronConfiguration: "[Xe]6s1",
    oxidationStates: "+1",
    electronegativity: 0.79,
    atomicRadius: "343 pm",
    ionizationEnergy: "3.894 eV",
    electronAffinity: "0.471 eV",
    meltingPoint: "301.59 K",
    boilingPoint: "944 K",
    density: "1.93 g/cm³",
    yearDiscovered: "1860",
    group: 1,
    period: 6,
    row: 6,
    column: 1,
  },
  {
    symbol: "Ba",
    name: "Barium",
    atomicNumber: 56,
    molarMass: 137.327,
    category: "Alkaline earth metal",
    standardState: "solid",
    electronConfiguration: "[Xe]6s2",
    oxidationStates: "+2",
    electronegativity: 0.89,
    atomicRadius: "268 pm",
    ionizationEnergy: "5.212 eV",
    meltingPoint: "1000 K",
    boilingPoint: "2170 K",
    density: "3.62 g/cm³",
    yearDiscovered: "1808",
    group: 2,
    period: 6,
    row: 6,
    column: 2,
  },
  {
    symbol: "La",
    name: "Lanthanum",
    atomicNumber: 57,
    molarMass: 138.90547,
    category: "Lanthanide",
    standardState: "solid",
    electronConfiguration: "[Xe]5d16s2",
    oxidationStates: "+3",
    electronegativity: 1.1,
    atomicRadius: "195 pm",
    ionizationEnergy: "5.577 eV",
    meltingPoint: "1191 K",
    boilingPoint: "3737 K",
    density: "6.15 g/cm³",
    yearDiscovered: "1839",
    group: 3,
    period: 6,
    row: 9,
    column: 4,
  },
  {
    symbol: "Ce",
    name: "Cerium",
    atomicNumber: 58,
    molarMass: 140.116,
    category: "Lanthanide",
    standardState: "solid",
    electronConfiguration: "[Xe]4f15d16s2",
    oxidationStates: "+4, +3",
    electronegativity: 1.12,
    atomicRadius: "185 pm",
    ionizationEnergy: "5.539 eV",
    meltingPoint: "1071 K",
    boilingPoint: "3697 K",
    density: "6.770 g/cm³",
    yearDiscovered: "1803",
    group: "Lanthanoid",
    period: 6,
    row: 9,
    column: 5,
  },
  {
    symbol: "Pr",
    name: "Praseodymium",
    atomicNumber: 59,
    molarMass: 140.90766,
    category: "Lanthanide",
    standardState: "solid",
    electronConfiguration: "[Xe]4f36s2",
    oxidationStates: "+3",
    electronegativity: 1.13,
    atomicRadius: "185 pm",
    ionizationEnergy: "5.464 eV",
    meltingPoint: "1204 K",
    boilingPoint: "3793 K",
    density: "6.77 g/cm³",
    yearDiscovered: "1885",
    group: "Lanthanoid",
    period: 6,
    row: 9,
    column: 6,
  },
  {
    symbol: "Nd",
    name: "Neodymium",
    atomicNumber: 60,
    molarMass: 144.242,
    category: "Lanthanide",
    standardState: "solid",
    electronConfiguration: "[Xe]4f46s2",
    oxidationStates: "+3",
    electronegativity: 1.14,
    atomicRadius: "185 pm",
    ionizationEnergy: "5.525 eV",
    meltingPoint: "1294 K",
    boilingPoint: "3347 K",
    density: "7.01 g/cm³",
    yearDiscovered: "1885",
    group: "Lanthanoid",
    period: 6,
    row: 9,
    column: 7,
  },
  {
    symbol: "Pm",
    name: "Promethium",
    atomicNumber: 61,
    molarMass: 145,
    category: "Lanthanide",
    standardState: "solid",
    electronConfiguration: "[Xe]4f56s2",
    oxidationStates: "+3",
    atomicRadius: "185 pm",
    ionizationEnergy: "5.55 eV",
    meltingPoint: "1315 K",
    boilingPoint: "3273 K",
    density: "7.26 g/cm³",
    yearDiscovered: "1945",
    group: "Lanthanoid",
    period: 6,
    row: 9,
    column: 8,
  },
  {
    symbol: "Sm",
    name: "Samarium",
    atomicNumber: 62,
    molarMass: 150.36,
    category: "Lanthanide",
    standardState: "solid",
    electronConfiguration: "[Xe]4f66s2",
    oxidationStates: "+3, +2",
    electronegativity: 1.17,
    atomicRadius: "185 pm",
    ionizationEnergy: "5.644 eV",
    meltingPoint: "1345 K",
    boilingPoint: "2067 K",
    density: "7.52 g/cm³",
    yearDiscovered: "1879",
    group: "Lanthanoid",
    period: 6,
    row: 9,
    column: 9,
  },
  {
    symbol: "Eu",
    name: "Europium",
    atomicNumber: 63,
    molarMass: 151.964,
    category: "Lanthanide",
    standardState: "solid",
    electronConfiguration: "[Xe]4f76s2",
    oxidationStates: "+3, +2",
    atomicRadius: "185 pm",
    ionizationEnergy: "5.670 eV",
    meltingPoint: "1095 K",
    boilingPoint: "1802 K",
    density: "5.24 g/cm³",
    yearDiscovered: "1901",
    group: "Lanthanoid",
    period: 6,
    row: 9,
    column: 10,
  },
  {
    symbol: "Gd",
    name: "Gadolinium",
    atomicNumber: 64,
    molarMass: 157.25,
    category: "Lanthanide",
    standardState: "solid",
    electronConfiguration: "[Xe]4f75d16s2",
    oxidationStates: "+3",
    electronegativity: 1.2,
    atomicRadius: "185 pm",
    ionizationEnergy: "6.150 eV",
    meltingPoint: "1586 K",
    boilingPoint: "3546 K",
    density: "7.90 g/cm³",
    yearDiscovered: "1880",
    group: "Lanthanoid",
    period: 6,
    row: 9,
    column: 11,
  },
  {
    symbol: "Tb",
    name: "Terbium",
    atomicNumber: 65,
    molarMass: 158.92535,
    category: "Lanthanide",
    standardState: "solid",
    electronConfiguration: "[Xe]4f96s2",
    oxidationStates: "+3",
    atomicRadius: "185 pm",
    ionizationEnergy: "5.864 eV",
    meltingPoint: "1629 K",
    boilingPoint: "3503 K",
    density: "8.23 g/cm³",
    yearDiscovered: "1843",
    group: "Lanthanoid",
    period: 6,
    row: 9,
    column: 12,
  },
  {
    symbol: "Dy",
    name: "Dysprosium",
    atomicNumber: 66,
    molarMass: 162.5,
    category: "Lanthanide",
    standardState: "solid",
    electronConfiguration: "[Xe]4f106s2",
    oxidationStates: "+3",
    electronegativity: 1.22,
    atomicRadius: "185 pm",
    ionizationEnergy: "5.939 eV",
    meltingPoint: "1685 K",
    boilingPoint: "2840 K",
    density: "8.55 g/cm³",
    yearDiscovered: "1886",
    group: "Lanthanoid",
    period: 6,
    row: 9,
    column: 13,
  },
  {
    symbol: "Ho",
    name: "Holmium",
    atomicNumber: 67,
    molarMass: 164.93033,
    category: "Lanthanide",
    standardState: "solid",
    electronConfiguration: "[Xe]4f116s2",
    oxidationStates: "+3",
    electronegativity: 1.23,
    atomicRadius: "185 pm",
    ionizationEnergy: "6.022 eV",
    meltingPoint: "1747 K",
    boilingPoint: "2973 K",
    density: "8.80 g/cm³",
    yearDiscovered: "1878",
    group: "Lanthanoid",
    period: 6,
    row: 9,
    column: 14,
  },
  {
    symbol: "Er",
    name: "Erbium",
    atomicNumber: 68,
    molarMass: 167.259,
    category: "Lanthanide",
    standardState: "solid",
    electronConfiguration: "[Xe]4f126s2",
    oxidationStates: "+3",
    electronegativity: 1.24,
    atomicRadius: "185 pm",
    ionizationEnergy: "6.108 eV",
    meltingPoint: "1802 K",
    boilingPoint: "3141 K",
    density: "9.07 g/cm³",
    yearDiscovered: "1843",
    group: "Lanthanoid",
    period: 6,
    row: 9,
    column: 15,
  },
  {
    symbol: "Tm",
    name: "Thulium",
    atomicNumber: 69,
    molarMass: 168.93422,
    category: "Lanthanide",
    standardState: "solid",
    electronConfiguration: "[Xe]4f136s2",
    oxidationStates: "+3",
    electronegativity: 1.25,
    atomicRadius: "185 pm",
    ionizationEnergy: "6.184 eV",
    meltingPoint: "1818 K",
    boilingPoint: "2223 K",
    density: "9.32 g/cm³",
    yearDiscovered: "1879",
    group: "Lanthanoid",
    period: 6,
    row: 9,
    column: 16,
  },
  {
    symbol: "Yb",
    name: "Ytterbium",
    atomicNumber: 70,
    molarMass: 173.045,
    category: "Lanthanide",
    standardState: "solid",
    electronConfiguration: "[Xe]4f146s2",
    oxidationStates: "+3, +2",
    atomicRadius: "185 pm",
    ionizationEnergy: "6.254 eV",
    meltingPoint: "1092 K",
    boilingPoint: "1469 K",
    density: "6.90 g/cm³",
    yearDiscovered: "1878",
    group: "Lanthanoid",
    period: 6,
    row: 9,
    column: 17,
  },
  {
    symbol: "Lu",
    name: "Lutetium",
    atomicNumber: 71,
    molarMass: 174.9668,
    category: "Lanthanide",
    standardState: "solid",
    electronConfiguration: "[Xe]4f145d16s2",
    oxidationStates: "+3",
    electronegativity: 1.27,
    atomicRadius: "185 pm",
    ionizationEnergy: "5.426 eV",
    meltingPoint: "1936 K",
    boilingPoint: "3675 K",
    density: "9.84 g/cm³",
    yearDiscovered: "1907",
    group: 3,
    period: 6,
    row: 9,
    column: 18,
  },
  {
    symbol: "Hf",
    name: "Hafnium",
    atomicNumber: 72,
    molarMass: 178.49,
    category: "Transition metal",
    standardState: "solid",
    electronConfiguration: "[Xe]4f145d26s2",
    oxidationStates: "+4",
    electronegativity: 1.3,
    atomicRadius: "212 pm",
    ionizationEnergy: "6.825 eV",
    meltingPoint: "2506 K",
    boilingPoint: "4876 K",
    density: "13.3 g/cm³",
    yearDiscovered: "1923",
    group: 4,
    period: 6,
    row: 6,
    column: 4,
  },
  {
    symbol: "Ta",
    name: "Tantalum",
    atomicNumber: 73,
    molarMass: 180.94788,
    category: "Transition metal",
    standardState: "solid",
    electronConfiguration: "[Xe]4f145d36s2",
    oxidationStates: "+5",
    electronegativity: 1.5,
    atomicRadius: "217 pm",
    ionizationEnergy: "7.89 eV",
    electronAffinity: "0.322 eV",
    meltingPoint: "3290 K",
    boilingPoint: "5731 K",
    density: "16.4 g/cm³",
    yearDiscovered: "1802",
    group: 5,
    period: 6,
    row: 6,
    column: 5,
  },
  {
    symbol: "W",
    name: "Tungsten",
    atomicNumber: 74,
    molarMass: 183.84,
    category: "Transition metal",
    standardState: "solid",
    electronConfiguration: "[Xe]4f145d46s2",
    oxidationStates: "+6",
    electronegativity: 2.36,
    atomicRadius: "210 pm",
    ionizationEnergy: "7.98 eV",
    electronAffinity: "0.815 eV",
    meltingPoint: "3695 K",
    boilingPoint: "5828 K",
    density: "19.3 g/cm³",
    yearDiscovered: "1783",
    group: 6,
    period: 6,
    row: 6,
    column: 6,
  },
  {
    symbol: "Re",
    name: "Rhenium",
    atomicNumber: 75,
    molarMass: 186.207,
    category: "Transition metal",
    standardState: "solid",
    electronConfiguration: "[Xe]4f145d56s2",
    oxidationStates: "+7, +6, +4",
    electronegativity: 1.9,
    atomicRadius: "217 pm",
    ionizationEnergy: "7.88 eV",
    electronAffinity: "0.15 eV",
    meltingPoint: "3459 K",
    boilingPoint: "5869 K",
    density: "20.8 g/cm³",
    yearDiscovered: "1925",
    group: 7,
    period: 6,
    row: 6,
    column: 7,
  },
  {
    symbol: "Os",
    name: "Osmium",
    atomicNumber: 76,
    molarMass: 190.23,
    category: "Transition metal",
    standardState: "solid",
    electronConfiguration: "[Xe]4f145d66s2",
    oxidationStates: "+4, +3",
    electronegativity: 2.2,
    atomicRadius: "216 pm",
    ionizationEnergy: "8.7 eV",
    electronAffinity: "1.1 eV",
    meltingPoint: "3306 K",
    boilingPoint: "5285 K",
    density: "22.57 g/cm³",
    yearDiscovered: "1803",
    group: 8,
    period: 6,
    row: 6,
    column: 8,
  },
  {
    symbol: "Ir",
    name: "Iridium",
    atomicNumber: 77,
    molarMass: 192.217,
    category: "Transition metal",
    standardState: "solid",
    electronConfiguration: "[Xe]4f145d76s2",
    oxidationStates: "+4, +3",
    electronegativity: 2.2,
    atomicRadius: "202 pm",
    ionizationEnergy: "9.1 eV",
    electronAffinity: "1.565 eV",
    meltingPoint: "2719 K",
    boilingPoint: "4701 K",
    density: "22.42 g/cm³",
    yearDiscovered: "1803",
    group: 9,
    period: 6,
    row: 6,
    column: 9,
  },
  {
    symbol: "Pt",
    name: "Platinum",
    atomicNumber: 78,
    molarMass: 195.084,
    category: "Transition metal",
    standardState: "solid",
    electronConfiguration: "[Xe]4f145d96s1",
    oxidationStates: "+4, +2",
    electronegativity: 2.28,
    atomicRadius: "209 pm",
    ionizationEnergy: "9.0 eV",
    electronAffinity: "2.128 eV",
    meltingPoint: "2041.55 K",
    boilingPoint: "4098 K",
    density: "21.46 g/cm³",
    yearDiscovered: "1735",
    group: 10,
    period: 6,
    row: 6,
    column: 10,
  },
  {
    symbol: "Au",
    name: "Gold",
    atomicNumber: 79,
    molarMass: 196.966569,
    category: "Transition metal",
    standardState: "solid",
    electronConfiguration: "[Xe]4f145d106s1",
    oxidationStates: "+3, +1",
    electronegativity: 2.54,
    atomicRadius: "166 pm",
    ionizationEnergy: "9.226 eV",
    electronAffinity: "2.309 eV",
    meltingPoint: "1337.33 K",
    boilingPoint: "3129 K",
    density: "19.282 g/cm³",
    yearDiscovered: "ancient",
    group: 11,
    period: 6,
    row: 6,
    column: 11,
  },
  {
    symbol: "Hg",
    name: "Mercury",
    atomicNumber: 80,
    molarMass: 200.592,
    category: "Transition metal",
    standardState: "liquid",
    electronConfiguration: "[Xe]4f145d106s2",
    oxidationStates: "+2, +1",
    electronegativity: 2.0,
    atomicRadius: "209 pm",
    ionizationEnergy: "10.438 eV",
    meltingPoint: "234.32 K",
    boilingPoint: "629.88 K",
    density: "13.5336 g/cm³",
    yearDiscovered: "ancient",
    group: 12,
    period: 6,
    row: 6,
    column: 12,
  },
  {
    symbol: "Tl",
    name: "Thallium",
    atomicNumber: 81,
    molarMass: 204.38,
    category: "Post-transition metal",
    standardState: "solid",
    electronConfiguration: "[Xe]4f145d106s26p1",
    oxidationStates: "+3, +1",
    electronegativity: 1.62,
    atomicRadius: "196 pm",
    ionizationEnergy: "6.108 eV",
    electronAffinity: "0.2 eV",
    meltingPoint: "577 K",
    boilingPoint: "1746 K",
    density: "11.85 g/cm³",
    yearDiscovered: "1861",
    group: 13,
    period: 6,
    row: 6,
    column: 13,
  },
  {
    symbol: "Pb",
    name: "Lead",
    atomicNumber: 82,
    molarMass: 207.2,
    category: "Post-transition metal",
    standardState: "solid",
    electronConfiguration: "[Xe]4f145d106s26p2",
    oxidationStates: "+4, +2",
    electronegativity: 2.33,
    atomicRadius: "202 pm",
    ionizationEnergy: "7.417 eV",
    electronAffinity: "0.36 eV",
    meltingPoint: "600.61 K",
    boilingPoint: "2022 K",
    density: "11.342 g/cm³",
    yearDiscovered: "ancient",
    group: 14,
    period: 6,
    row: 6,
    column: 14,
  },
  {
    symbol: "Bi",
    name: "Bismuth",
    atomicNumber: 83,
    molarMass: 208.9804,
    category: "Post-transition metal",
    standardState: "solid",
    electronConfiguration: "[Xe]4f145d106s26p3",
    oxidationStates: "+5, +3",
    electronegativity: 2.02,
    atomicRadius: "207 pm",
    ionizationEnergy: "7.289 eV",
    electronAffinity: "0.946 eV",
    meltingPoint: "544.55 K",
    boilingPoint: "1837 K",
    density: "9.807 g/cm³",
    yearDiscovered: "1753",
    group: 15,
    period: 6,
    row: 6,
    column: 15,
  },
  {
    symbol: "Po",
    name: "Polonium",
    atomicNumber: 84,
    molarMass: 209,
    category: "Post-transition metal",
    standardState: "solid",
    electronConfiguration: "[Xe]4f145d106s26p4",
    oxidationStates: "+4, +2",
    electronegativity: 2.0,
    atomicRadius: "197 pm",
    ionizationEnergy: "8.417 eV",
    electronAffinity: "1.9 eV",
    meltingPoint: "527 K",
    boilingPoint: "1235 K",
    density: "9.32 g/cm³",
    yearDiscovered: "1898",
    group: 16,
    period: 6,
    row: 6,
    column: 16,
  },
  {
    symbol: "At",
    name: "Astatine",
    atomicNumber: 85,
    molarMass: 210,
    category: "Halogen",
    standardState: "solid",
    electronConfiguration: "[Xe]4f145d106s26p5",
    oxidationStates: "+7, +5, +3, +1, -1",
    electronegativity: 2.2,
    atomicRadius: "202 pm",
    ionizationEnergy: "9.5 eV",
    electronAffinity: "2.8 eV",
    meltingPoint: "575 K",
    density: "7 g/cm³",
    yearDiscovered: "1940",
    group: 17,
    period: 6,
    row: 6,
    column: 17,
  },
  {
    symbol: "Rn",
    name: "Radon",
    atomicNumber: 86,
    molarMass: 222,
    category: "Noble gas",
    standardState: "gas",
    electronConfiguration: "[Xe]4f145d106s26p6",
    oxidationStates: "0",
    atomicRadius: "220 pm",
    ionizationEnergy: "10.745 eV",
    meltingPoint: "202 K",
    boilingPoint: "211.45 K",
    density: "0.00973 g/cm³",
    yearDiscovered: "1900",
    group: 18,
    period: 6,
    row: 6,
    column: 18,
  },
  {
    symbol: "Fr",
    name: "Francium",
    atomicNumber: 87,
    molarMass: 223,
    category: "Alkali metal",
    standardState: "solid",
    electronConfiguration: "[Rn]7s1",
    oxidationStates: "+1",
    electronegativity: 0.7,
    atomicRadius: "348 pm",
    ionizationEnergy: "3.9 eV",
    electronAffinity: "0.47 eV",
    meltingPoint: "300 K",
    yearDiscovered: "1939",
    group: 1,
    period: 7,
    row: 7,
    column: 1,
  },
  {
    symbol: "Ra",
    name: "Radium",
    atomicNumber: 88,
    molarMass: 226,
    category: "Alkaline earth metal",
    standardState: "solid",
    electronConfiguration: "[Rn]7s2",
    oxidationStates: "+2",
    electronegativity: 0.9,
    atomicRadius: "283 pm",
    ionizationEnergy: "5.279 eV",
    meltingPoint: "973 K",
    boilingPoint: "1413 K",
    density: "5 g/cm³",
    yearDiscovered: "1898",
    group: 2,
    period: 7,
    row: 7,
    column: 2,
  },
  {
    symbol: "Ac",
    name: "Actinium",
    atomicNumber: 89,
    molarMass: 227,
    category: "Actinide",
    standardState: "solid",
    electronConfiguration: "[Rn]6d17s2",
    oxidationStates: "+3",
    electronegativity: 1.1,
    atomicRadius: "260 pm",
    ionizationEnergy: "5.17 eV",
    meltingPoint: "1324 K",
    boilingPoint: "3471 K",
    density: "10.07 g/cm³",
    yearDiscovered: "1899",
    group: 3,
    period: 7,
    row: 10,
    column: 4,
  },
  {
    symbol: "Th",
    name: "Thorium",
    atomicNumber: 90,
    molarMass: 232.0377,
    category: "Actinide",
    standardState: "solid",
    electronConfiguration: "[Rn]6d27s2",
    oxidationStates: "+4",
    electronegativity: 1.3,
    atomicRadius: "237 pm",
    ionizationEnergy: "6.08 eV",
    meltingPoint: "2023 K",
    boilingPoint: "5061 K",
    density: "11.72 g/cm³",
    yearDiscovered: "1828",
    group: "Actinoid",
    period: 7,
    row: 10,
    column: 5,
  },
  {
    symbol: "Pa",
    name: "Protactinium",
    atomicNumber: 91,
    molarMass: 231.03588,
    category: "Actinide",
    standardState: "solid",
    electronConfiguration: "[Rn]5f26d17s2",
    oxidationStates: "+5, +4",
    electronegativity: 1.5,
    atomicRadius: "243 pm",
    ionizationEnergy: "5.89 eV",
    meltingPoint: "1845 K",
    density: "15.37 g/cm³",
    yearDiscovered: "1913",
    group: "Actinoid",
    period: 7,
    row: 10,
    column: 6,
  },
  {
    symbol: "U",
    name: "Uranium",
    atomicNumber: 92,
    molarMass: 238.02891,
    category: "Actinide",
    standardState: "solid",
    electronConfiguration: "[Rn]5f36d17s2",
    oxidationStates: "+6, +5, +4, +3",
    electronegativity: 1.38,
    atomicRadius: "240 pm",
    ionizationEnergy: "6.194 eV",
    meltingPoint: "1408 K",
    boilingPoint: "4404 K",
    density: "18.95 g/cm³",
    yearDiscovered: "1789",
    group: "Actinoid",
    period: 7,
    row: 10,
    column: 7,
  },
  {
    symbol: "Np",
    name: "Neptunium",
    atomicNumber: 93,
    molarMass: 237,
    category: "Actinide",
    standardState: "solid",
    electronConfiguration: "[Rn]5f46d17s2",
    oxidationStates: "+6, +5, +4, +3",
    electronegativity: 1.36,
    atomicRadius: "221 pm",
    ionizationEnergy: "6.266 eV",
    meltingPoint: "917 K",
    boilingPoint: "4175 K",
    density: "20.25 g/cm³",
    yearDiscovered: "1940",
    group: "Actinoid",
    period: 7,
    row: 10,
    column: 8,
  },
  {
    symbol: "Pu",
    name: "Plutonium",
    atomicNumber: 94,
    molarMass: 244,
    category: "Actinide",
    standardState: "solid",
    electronConfiguration: "[Rn]5f67s2",
    oxidationStates: "+6, +5, +4, +3",
    electronegativity: 1.28,
    atomicRadius: "243 pm",
    ionizationEnergy: "6.06 eV",
    meltingPoint: "913 K",
    boilingPoint: "3501 K",
    density: "19.84 g/cm³",
    yearDiscovered: "1940",
    group: "Actinoid",
    period: 7,
    row: 10,
    column: 9,
  },
  {
    symbol: "Am",
    name: "Americium",
    atomicNumber: 95,
    molarMass: 243,
    category: "Actinide",
    standardState: "solid",
    electronConfiguration: "[Rn]5f77s2",
    oxidationStates: "+6, +5, +4, +3",
    electronegativity: 1.3,
    atomicRadius: "244 pm",
    ionizationEnergy: "5.993 eV",
    meltingPoint: "1449 K",
    boilingPoint: "2284 K",
    density: "13.69 g/cm³",
    yearDiscovered: "1944",
    group: "Actinoid",
    period: 7,
    row: 10,
    column: 10,
  },
  {
    symbol: "Cm",
    name: "Curium",
    atomicNumber: 96,
    molarMass: 247,
    category: "Actinide",
    standardState: "solid",
    electronConfiguration: "[Rn]5f76d17s2",
    oxidationStates: "+3",
    electronegativity: 1.3,
    atomicRadius: "245 pm",
    ionizationEnergy: "6.02 eV",
    meltingPoint: "1618 K",
    boilingPoint: "3400 K",
    density: "13.51 g/cm³",
    yearDiscovered: "1944",
    group: "Actinoid",
    period: 7,
    row: 10,
    column: 11,
  },
  {
    symbol: "Bk",
    name: "Berkelium",
    atomicNumber: 97,
    molarMass: 247,
    category: "Actinide",
    standardState: "solid",
    electronConfiguration: "[Rn]5f97s2",
    oxidationStates: "+4, +3",
    electronegativity: 1.3,
    atomicRadius: "244 pm",
    ionizationEnergy: "6.23 eV",
    meltingPoint: "1323 K",
    density: "14 g/cm³",
    yearDiscovered: "1949",
    group: "Actinoid",
    period: 7,
    row: 10,
    column: 12,
  },
  {
    symbol: "Cf",
    name: "Californium",
    atomicNumber: 98,
    molarMass: 251,
    category: "Actinide",
    standardState: "solid",
    electronConfiguration: "[Rn]5f107s2",
    oxidationStates: "+3",
    electronegativity: 1.3,
    atomicRadius: "245 pm",
    ionizationEnergy: "6.30 eV",
    meltingPoint: "1173 K",
    yearDiscovered: "1950",
    group: "Actinoid",
    period: 7,
    row: 10,
    column: 13,
  },
  {
    symbol: "Es",
    name: "Einsteinium",
    atomicNumber: 99,
    molarMass: 252,
    category: "Actinide",
    standardState: "solid",
    electronConfiguration: "[Rn]5f117s2",
    oxidationStates: "+3",
    electronegativity: 1.3,
    atomicRadius: "245 pm",
    ionizationEnergy: "6.42 eV",
    meltingPoint: "1133 K",
    yearDiscovered: "1952",
    group: "Actinoid",
    period: 7,
    row: 10,
    column: 14,
  },
  {
    symbol: "Fm",
    name: "Fermium",
    atomicNumber: 100,
    molarMass: 257,
    category: "Actinide",
    standardState: "solid",
    electronConfiguration: "[Rn]5f127s2",
    oxidationStates: "+3",
    electronegativity: 1.3,
    ionizationEnergy: "6.50 eV",
    meltingPoint: "1800 K",
    yearDiscovered: "1952",
    group: "Actinoid",
    period: 7,
    row: 10,
    column: 15,
  },
  {
    symbol: "Md",
    name: "Mendelevium",
    atomicNumber: 101,
    molarMass: 258,
    category: "Actinide",
    standardState: "solid",
    electronConfiguration: "[Rn]5f137s2",
    oxidationStates: "+3, +2",
    electronegativity: 1.3,
    ionizationEnergy: "6.58 eV",
    meltingPoint: "1100 K",
    yearDiscovered: "1955",
    group: "Actinoid",
    period: 7,
    row: 10,
    column: 16,
  },
  {
    symbol: "No",
    name: "Nobelium",
    atomicNumber: 102,
    molarMass: 259,
    category: "Actinide",
    standardState: "solid",
    electronConfiguration: "[Rn]5f147s2",
    oxidationStates: "+3, +2",
    electronegativity: 1.3,
    ionizationEnergy: "6.65 eV",
    meltingPoint: "1100 K",
    yearDiscovered: "1957",
    group: "Actinoid",
    period: 7,
    row: 10,
    column: 17,
  },
  {
    symbol: "Lr",
    name: "Lawrencium",
    atomicNumber: 103,
    molarMass: 266,
    category: "Actinide",
    standardState: "solid",
    electronConfiguration: "[Rn]5f147s26d1",
    oxidationStates: "+3",
    electronegativity: 1.3,
    meltingPoint: "1900 K",
    yearDiscovered: "1961",
    group: 3,
    period: 7,
    row: 10,
    column: 18,
  },
  {
    symbol: "Rf",
    name: "Rutherfordium",
    atomicNumber: 104,
    molarMass: 267,
    category: "Transition metal",
    standardState: "solid",
    electronConfiguration: "[Rn]5f146d27s2",
    oxidationStates: "+4",
    yearDiscovered: "1964",
    group: 4,
    period: 7,
    row: 7,
    column: 4,
  },
  {
    symbol: "Db",
    name: "Dubnium",
    atomicNumber: 105,
    molarMass: 270,
    category: "Transition metal",
    standardState: "solid",
    electronConfiguration: "[Rn]5f146d37s2",
    oxidationStates: "+5",
    yearDiscovered: "1967",
    group: 5,
    period: 7,
    row: 7,
    column: 5,
  },
  {
    symbol: "Sg",
    name: "Seaborgium",
    atomicNumber: 106,
    molarMass: 271,
    category: "Transition metal",
    standardState: "solid",
    electronConfiguration: "[Rn]5f146d47s2",
    oxidationStates: "+6",
    yearDiscovered: "1974",
    group: 6,
    period: 7,
    row: 7,
    column: 6,
  },
  {
    symbol: "Bh",
    name: "Bohrium",
    atomicNumber: 107,
    molarMass: 270,
    category: "Transition metal",
    standardState: "solid",
    electronConfiguration: "[Rn]5f146d57s2",
    oxidationStates: "+7",
    yearDiscovered: "1976",
    group: 7,
    period: 7,
    row: 7,
    column: 7,
  },
  {
    symbol: "Hs",
    name: "Hassium",
    atomicNumber: 108,
    molarMass: 277,
    category: "Transition metal",
    standardState: "solid",
    electronConfiguration: "[Rn]5f146d67s2",
    oxidationStates: "+8",
    yearDiscovered: "1984",
    group: 8,
    period: 7,
    row: 7,
    column: 8,
  },
  {
    symbol: "Mt",
    name: "Meitnerium",
    atomicNumber: 109,
    molarMass: 278,
    category: "Transition metal",
    standardState: "solid",
    electronConfiguration: "[Rn]5f146d77s2",
    yearDiscovered: "1982",
    group: 9,
    period: 7,
    row: 7,
    column: 9,
  },
  {
    symbol: "Ds",
    name: "Darmstadtium",
    atomicNumber: 110,
    molarMass: 281,
    category: "Transition metal",
    standardState: "solid",
    electronConfiguration: "[Rn]5f146d87s2",
    yearDiscovered: "1994",
    group: 10,
    period: 7,
    row: 7,
    column: 10,
  },
  {
    symbol: "Rg",
    name: "Roentgenium",
    atomicNumber: 111,
    molarMass: 282,
    category: "Transition metal",
    standardState: "solid",
    electronConfiguration: "[Rn]5f146d97s2",
    yearDiscovered: "1994",
    group: 11,
    period: 7,
    row: 7,
    column: 11,
  },
  {
    symbol: "Cn",
    name: "Copernicium",
    atomicNumber: 112,
    molarMass: 285,
    category: "Transition metal",
    standardState: "solid",
    electronConfiguration: "[Rn]5f146d107s2",
    yearDiscovered: "1996",
    group: 12,
    period: 7,
    row: 7,
    column: 12,
  },
  {
    symbol: "Nh",
    name: "Nihonium",
    atomicNumber: 113,
    molarMass: 286,
    category: "Post-transition metal",
    standardState: "solid",
    electronConfiguration: "[Rn]5f146d107s27p1",
    yearDiscovered: "2004",
    group: 13,
    period: 7,
    row: 7,
    column: 13,
  },
  {
    symbol: "Fl",
    name: "Flerovium",
    atomicNumber: 114,
    molarMass: 289,
    category: "Post-transition metal",
    standardState: "solid",
    electronConfiguration: "[Rn]5f146d107s27p2",
    yearDiscovered: "1998",
    group: 14,
    period: 7,
    row: 7,
    column: 14,
  },
  {
    symbol: "Mc",
    name: "Moscovium",
    atomicNumber: 115,
    molarMass: 290,
    category: "Post-transition metal",
    standardState: "solid",
    electronConfiguration: "[Rn]5f146d107s27p3",
    yearDiscovered: "2003",
    group: 15,
    period: 7,
    row: 7,
    column: 15,
  },
  {
    symbol: "Lv",
    name: "Livermorium",
    atomicNumber: 116,
    molarMass: 293,
    category: "Post-transition metal",
    standardState: "solid",
    electronConfiguration: "[Rn]5f146d107s27p4",
    yearDiscovered: "2000",
    group: 16,
    period: 7,
    row: 7,
    column: 16,
  },
  {
    symbol: "Ts",
    name: "Tennessine",
    atomicNumber: 117,
    molarMass: 294,
    category: "Halogen",
    standardState: "solid",
    electronConfiguration: "[Rn]5f146d107s27p5",
    yearDiscovered: "2010",
    group: 17,
    period: 7,
    row: 7,
    column: 17,
  },
  {
    symbol: "Og",
    name: "Oganesson",
    atomicNumber: 118,
    molarMass: 294,
    category: "Noble gas",
    standardState: "gas",
    electronConfiguration: "[Rn]5f146d107s27p6",
    yearDiscovered: "2006",
    group: 18,
    period: 7,
    row: 7,
    column: 18,
  },
];
export default elementsData;
